// WorldData
//
// This file is generated by `gulp buildAssets`.

/* <generated-constants> */
export const $D_DINING = 1;
export const $D_DINING_OPEN = 2;
export const $D_DRAW = 3;
export const $D_FOYER = 4;
export const $D_GARAGE = 5;
export const $D_HALLWAY = 6;
export const $D_KITCHEN = 7;
export const $F_BURNT_CHAIR = 8;
export const $F_BURNT_CHAIR_A = 9;
export const $F_DOLLHOUSE = 10;
export const $F_DOLLHOUSE_A = 11;
export const $F_FIRE1 = 12;
export const $F_FIRE2 = 13;
export const $F_FIRE3 = 14;
export const $F_FIRE3_A = 15;
export const $F_FIRE3_B = 16;
export const $F_SHELF1 = 17;
export const $F_SHELF2 = 18;
export const $F_SHELF3 = 19;
export const $F_SHELF3_A = 20;
export const $F_STAIR1 = 21;
export const $F_STATUE = 22;
export const $F_STATUE_A = 23;
export const $F_STATUE_B = 24;
export const $I_BURNT_NOTEBOOK = 44;
export const $I_DOLL_WORKBENCH = 45;
export const $I_IRON_KNIFE = 41;
export const $I_SILVER_KEY = 42;
export const $I_UNCLE_LETTER = 43;
export const $R_DINING = 30;
export const $R_DRAW = 31;
export const $R_FOYER = 32;
export const $R_GARAGE = 33;
export const $R_HALLWAY = 34;
export const $R_STUDY = 35;
/* </generated-constants> */

export const WorldData =
/* <generated-data> */
{
    "floors": [
        {
            "name": "1F",
            "tiles": [
                [
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32
                ],
                [
                    32,
                    32,
                    32,
                    129,
                    129,
                    129,
                    129,
                    129,
                    129,
                    129,
                    134,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32
                ],
                [
                    32,
                    32,
                    32,
                    128,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    137,
                    129,
                    129,
                    129,
                    45,
                    129,
                    129,
                    129,
                    129,
                    134,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32
                ],
                [
                    32,
                    32,
                    32,
                    128,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    124,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    93,
                    128,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32
                ],
                [
                    32,
                    32,
                    32,
                    128,
                    46,
                    46,
                    166,
                    46,
                    46,
                    168,
                    137,
                    129,
                    129,
                    129,
                    45,
                    135,
                    129,
                    129,
                    129,
                    131,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32
                ],
                [
                    32,
                    32,
                    32,
                    129,
                    129,
                    129,
                    129,
                    129,
                    129,
                    129,
                    138,
                    46,
                    46,
                    46,
                    46,
                    128,
                    32,
                    32,
                    32,
                    133,
                    129,
                    134,
                    32,
                    32,
                    130,
                    129,
                    129,
                    129,
                    45,
                    129,
                    129,
                    138,
                    32
                ],
                [
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    133,
                    131,
                    46,
                    35,
                    35,
                    46,
                    137,
                    129,
                    135,
                    129,
                    131,
                    37,
                    132,
                    129,
                    129,
                    138,
                    61,
                    61,
                    46,
                    46,
                    46,
                    61,
                    128,
                    32
                ],
                [
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    128,
                    37,
                    46,
                    35,
                    35,
                    46,
                    128,
                    60,
                    132,
                    46,
                    46,
                    46,
                    46,
                    35,
                    46,
                    128,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    132,
                    134
                ],
                [
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    132,
                    134,
                    46,
                    35,
                    35,
                    46,
                    128,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    124,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    37,
                    128
                ],
                [
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    128,
                    46,
                    46,
                    46,
                    46,
                    124,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    128,
                    91,
                    93,
                    46,
                    46,
                    38,
                    46,
                    133,
                    131
                ],
                [
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    132,
                    129,
                    129,
                    129,
                    129,
                    138,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    38,
                    46,
                    137,
                    129,
                    129,
                    145,
                    129,
                    129,
                    129,
                    131,
                    32
                ],
                [
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    132,
                    129,
                    129,
                    129,
                    45,
                    129,
                    129,
                    129,
                    129,
                    131,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32
                ],
                [
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32
                ],
                [
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32
                ]
            ],
            "rooms": [
                [
                    33,
                    3,
                    1,
                    8,
                    5
                ],
                [
                    31,
                    25,
                    5,
                    8,
                    6
                ],
                [
                    30,
                    10,
                    4,
                    6,
                    7
                ],
                [
                    32,
                    19,
                    5,
                    3,
                    2
                ],
                [
                    34,
                    10,
                    2,
                    10,
                    3
                ],
                [
                    32,
                    15,
                    6,
                    10,
                    6
                ],
                [
                    31,
                    24,
                    5,
                    4,
                    2
                ],
                [
                    30,
                    9,
                    6,
                    2,
                    3
                ]
            ],
            "objects": [
                [
                    3,
                    24,
                    8,
                    2
                ],
                [
                    6,
                    14,
                    4,
                    2
                ],
                [
                    12,
                    20,
                    6
                ],
                [
                    14,
                    31,
                    8
                ],
                [
                    1,
                    15,
                    9,
                    2
                ],
                [
                    13,
                    10,
                    7
                ],
                [
                    10,
                    22,
                    7
                ],
                [
                    5,
                    10,
                    3,
                    2
                ],
                [
                    7,
                    14,
                    2,
                    2
                ],
                [
                    17,
                    6,
                    4
                ],
                [
                    4,
                    19,
                    11,
                    2
                ],
                [
                    21,
                    16,
                    7
                ],
                [
                    22,
                    29,
                    9
                ],
                [
                    8,
                    18,
                    3
                ],
                [
                    18,
                    25,
                    6
                ],
                [
                    19,
                    26,
                    6
                ]
            ],
            "triggers": [],
            "id": 0
        }
    ],
    "bounds": [
        [
            0,
            0
        ],
        [
            33,
            14
        ]
    ],
    "spawn": [
        19,
        9,
        0
    ],
    "strings": [
        0,
        "The lock is broken and the door won't budge. With the right tool, you can\nprobably pry it open.",
        "You wedge the knife between the door and frame. With a little effort, you\nforce the broken lock away from the strike plate.\n%y%0 You push the door open.",
        0,
        "The door has jammed behind you and won't budge.",
        0,
        0,
        "It seems to be locked from the other side.",
        "The charred remnants of a rocking chair.\nA half-burnt notebook is resting on the melted seat cushion.",
        "The charred remnants of a rocking chair.",
        "A vintage dollhouse. Normally you could open it up and take a look inside,\nbut it's been locked with a small silver padlock.",
        "You need some kind of key to open this.",
        "A massive stone fireplace. Above it hangs a portrait of a woman with long,\nstraight black hair. She has one hand on her visibly pregnant belly.\nThe embers are cold.",
        "An impressive granite fireplace. Above the mantle hangs a brightly colored\npainting of a newborn, out of place in such a drab room.\nThe embers are cold.",
        "Above a brick-and-onyx hearth hangs an unpleasant painting of a small child\nbeing devoured whole by a tall, dimly-lit creature. It is hard to look at.\nA knife has been left jammed into the canvas. You can probably pull it out.",
        "With a tug, the painting releases a long iron knife. Hundreds of tiny\nsymbols have been etched up and down the blade, but you don't recognize them.\n%y%0 You have obtained iron knife.",
        "Above a brick-and-onyx hearth hangs an unpleasant painting of a small child\nbeing devoured whole by a tall, dimly-lit creature. It is hard to look at.\nThe embers are cold.",
        "A rusty garage shelf.",
        "The shelf is covered with dust, but not much else.",
        "The shelf seems to have been recently used, most of the dust is wiped off.\nA realistic miniature workbench rests on the shelf.",
        "The shelf seems to have been recently used, most of the dust is wiped off.",
        "The stairs to the second floor are a wreck - you can't go up this way.",
        "A crude, life-sized sculpture of a pregnant woman. One hand rests on her\nbelly, and the other holds an iron knife.\nThe sculpture's grip looks loose - perhaps you could take the knife.",
        "With a tug, the sculpture releases the knife.\n%y%0 You have obtained iron knife.",
        "A crude, life-sized sculpture of a pregnant woman. One hand rests on her\nbelly.",
        0,
        0,
        0,
        0,
        0,
        [
            "DINING ROOM",
            "The dining room is dominated by an oak table, which appears to have been\nused recently as a butcher's block. Flies buzz above fresh animal entrails\nlittering the table. The table and the carpet below is soaked in blood."
        ],
        [
            "DRAWING ROOM",
            "You are in a dimly lit drawing room filled with faded furniture.\nThe room smells of musty upholstery."
        ],
        [
            "FOYER",
            "You are in the foyer of the farmhouse. The peeling paint and threadbare\nrugs make it seem older than the outside of the house.\nA large dollhouse sits on a pedestal in the far corner of the room."
        ],
        [
            "GARAGE",
            "The garage is empty, save for a few rusty shelves and the usual cobwebs.\nThere must have been other furniture here recently, you can see lines\nin the dust where a workbench used to be."
        ],
        [
            "CHARRED HALLWAY",
            "There must have been a fire at some point. Soot and grime coat the walls,\nand the air stinks of burnt fabric."
        ],
        [
            "???",
            "A nice old room.\nWhat a nice place it is.\nFuck it."
        ],
        0,
        0,
        0,
        0,
        0,
        [
            "iron knife",
            "A large iron knife etched with\nhundreds of tiny symbols. It feels\nheavy in your hand."
        ],
        [
            "silver key",
            "A small, delicate silver key."
        ],
        [
            "your uncle's letter",
            "Dearest Emily,\n\nYou may think me mad but I need\nyour help. We all do. Together\nwe can stop them or it's not\n[the rest is crossed out...]"
        ],
        [
            "a half-burnt notebook",
            "Most of the pages are too burnt\nto read, but somehow one page\nis crystal clear:\n\n\"Our Goddess walks the hills\n in the shadow of the wailing star\n and we follow in her path\""
        ],
        [
            "miniature workbench",
            "A curiously realistic miniature\nworkbench, made of wood and metal.\nMaybe there's some use for it."
        ]
    ]
}
/* </generated-data> */
;
