// WorldData
//
// This file is generated by `gulp buildAssets`.

/* <generated-constants> */
export const $D_CLOSET = 1;
export const $D_CLOSET_OPEN = 2;
export const $D_DINING = 3;
export const $D_DINING_OPEN = 4;
export const $D_DRAW = 5;
export const $D_FOYER = 6;
export const $D_GARAGE = 7;
export const $D_GARAGED = 8;
export const $D_HALLWAY = 9;
export const $D_KITCHEN = 10;
export const $D_STUDY = 11;
export const $F_ALTAR = 12;
export const $F_ALTAR_A = 13;
export const $F_BURNT_CHAIR = 14;
export const $F_BURNT_CHAIR_A = 15;
export const $F_CHAIR1 = 16;
export const $F_DOLLHOUSE = 17;
export const $F_DOLLHOUSE_A = 18;
export const $F_DOLLHOUSE_B = 19;
export const $F_DOLLHOUSE_C = 20;
export const $F_DOLLHOUSE_D = 21;
export const $F_DRAWER1 = 22;
export const $F_DRAWER1_A = 23;
export const $F_GRAFFITI = 24;
export const $F_PAINTING1 = 25;
export const $F_SHELF1 = 26;
export const $F_SHELF2 = 27;
export const $F_SHELF3 = 28;
export const $F_SHELF3_A = 29;
export const $F_SHELF4 = 30;
export const $F_STAIR1 = 31;
export const $F_STATUE = 32;
export const $F_STATUE_A = 33;
export const $F_STATUE_B = 34;
export const $F_TABLE = 35;
export const $H_STATUE2 = 36;
export const $H_STATUE2_A = 37;
export const $H_STATUE2_B = 38;
export const $H_WORKBENCH = 39;
export const $H_WORKBENCH_A = 40;
export const $I_BURNT_NOTEBOOK = 64;
export const $I_DOLL_SCULPTURE = 66;
export const $I_DOLL_WORKBENCH = 65;
export const $I_ENGRAVED_COIN = 44;
export const $I_IRON_KNIFE = 61;
export const $I_SCREWDRIVER = 67;
export const $I_SILVER_KEY = 62;
export const $I_UNCLE_LETTER = 63;
export const $R_CLOSET = 49;
export const $R_DINING = 50;
export const $R_DRAW = 51;
export const $R_FOYER = 52;
export const $R_GARAGE = 53;
export const $R_GARAGE_A = 54;
export const $R_HALLWAY = 55;
/* </generated-constants> */

export const WorldData =
/* <generated-data> */
{
    "floors": [
        {
            "name": "1F",
            "tiles": [
                [
                    32,
                    32,
                    32,
                    129,
                    129,
                    129,
                    129,
                    129,
                    129,
                    129,
                    134,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32
                ],
                [
                    32,
                    32,
                    32,
                    128,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    137,
                    129,
                    129,
                    45,
                    129,
                    129,
                    129,
                    129,
                    129,
                    134,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32
                ],
                [
                    32,
                    32,
                    32,
                    128,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    124,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    93,
                    137,
                    129,
                    134,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32
                ],
                [
                    32,
                    32,
                    32,
                    128,
                    46,
                    46,
                    166,
                    46,
                    46,
                    168,
                    137,
                    129,
                    45,
                    129,
                    129,
                    135,
                    45,
                    129,
                    129,
                    131,
                    46,
                    132,
                    129,
                    129,
                    134,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32
                ],
                [
                    32,
                    32,
                    32,
                    129,
                    129,
                    129,
                    129,
                    129,
                    129,
                    129,
                    138,
                    46,
                    46,
                    46,
                    46,
                    128,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    167,
                    137,
                    129,
                    129,
                    129,
                    45,
                    129,
                    129,
                    138,
                    32
                ],
                [
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    128,
                    46,
                    35,
                    37,
                    46,
                    137,
                    129,
                    135,
                    129,
                    129,
                    129,
                    129,
                    129,
                    129,
                    138,
                    61,
                    61,
                    46,
                    46,
                    46,
                    61,
                    128,
                    32
                ],
                [
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    133,
                    131,
                    46,
                    37,
                    35,
                    46,
                    128,
                    60,
                    132,
                    46,
                    46,
                    46,
                    46,
                    35,
                    46,
                    128,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    132,
                    134
                ],
                [
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    128,
                    46,
                    46,
                    35,
                    37,
                    46,
                    128,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    124,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    38,
                    128
                ],
                [
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    132,
                    134,
                    46,
                    46,
                    46,
                    46,
                    124,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    128,
                    91,
                    46,
                    46,
                    46,
                    46,
                    46,
                    133,
                    131
                ],
                [
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    132,
                    129,
                    129,
                    129,
                    129,
                    138,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    46,
                    137,
                    129,
                    129,
                    145,
                    145,
                    145,
                    129,
                    131,
                    32
                ],
                [
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    132,
                    129,
                    129,
                    129,
                    45,
                    129,
                    129,
                    145,
                    129,
                    131,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32,
                    32
                ]
            ],
            "rooms": [
                [
                    53,
                    3,
                    0,
                    8,
                    5
                ],
                [
                    51,
                    25,
                    4,
                    8,
                    6
                ],
                [
                    50,
                    10,
                    3,
                    6,
                    7
                ],
                [
                    55,
                    10,
                    1,
                    10,
                    3
                ],
                [
                    52,
                    15,
                    5,
                    10,
                    6
                ],
                [
                    51,
                    24,
                    4,
                    4,
                    2
                ],
                [
                    50,
                    9,
                    6,
                    2,
                    3
                ],
                [
                    49,
                    15,
                    3,
                    10,
                    2
                ],
                [
                    49,
                    19,
                    2,
                    3,
                    2
                ]
            ],
            "objects": [
                [
                    5,
                    24,
                    7
                ],
                [
                    9,
                    12,
                    3,
                    2
                ],
                [
                    3,
                    15,
                    8,
                    2
                ],
                [
                    17,
                    22,
                    6
                ],
                [
                    7,
                    10,
                    2,
                    2
                ],
                [
                    10,
                    13,
                    1,
                    2
                ],
                [
                    26,
                    6,
                    3,
                    4
                ],
                [
                    6,
                    19,
                    10,
                    2
                ],
                [
                    31,
                    16,
                    6,
                    4
                ],
                [
                    32,
                    31,
                    7
                ],
                [
                    14,
                    18,
                    2
                ],
                [
                    27,
                    25,
                    5,
                    4
                ],
                [
                    28,
                    26,
                    5
                ],
                [
                    8,
                    3,
                    3
                ],
                [
                    8,
                    3,
                    2
                ],
                [
                    8,
                    3,
                    1
                ],
                [
                    22,
                    9,
                    3
                ],
                [
                    39,
                    7,
                    3,
                    3
                ],
                [
                    39,
                    8,
                    3,
                    3
                ],
                [
                    24,
                    27,
                    9
                ],
                [
                    24,
                    28,
                    9
                ],
                [
                    24,
                    29,
                    9
                ],
                [
                    16,
                    25,
                    8,
                    4
                ],
                [
                    30,
                    30,
                    5,
                    4
                ],
                [
                    36,
                    10,
                    7,
                    3
                ],
                [
                    1,
                    16,
                    3,
                    2
                ],
                [
                    12,
                    23,
                    4
                ],
                [
                    25,
                    22,
                    10,
                    4
                ],
                [
                    11,
                    28,
                    4,
                    2
                ],
                [
                    35,
                    13,
                    7
                ],
                [
                    35,
                    12,
                    5
                ],
                [
                    35,
                    13,
                    6
                ],
                [
                    35,
                    12,
                    7
                ],
                [
                    35,
                    12,
                    6
                ],
                [
                    35,
                    13,
                    5
                ]
            ],
            "triggers": [],
            "id": 0
        }
    ],
    "bounds": [
        [
            0,
            0
        ],
        [
            33,
            11
        ]
    ],
    "spawn": [
        19,
        8,
        0
    ],
    "strings": [
        0,
        "The door is barred by a metal plate, held in place by a series of screws.\nYou could open it with the right tool.",
        "You unscrew several screws and the metal plate clatters to the floor.\n%y%0 You push the door open.",
        "The lock is broken and the door won't budge. With the right tool, you can\nprobably pry it open.",
        "You wedge the knife between the door and frame. With a little effort, you\nforce the broken lock away from the strike plate.\n%y%0 You push the door open.",
        0,
        "The front door has jammed behind you and won't budge.",
        0,
        "The garage door is heavy and immobile. In the center of the door is\na spray-painted eye, surrounded by rings of tiny symbols. It's hard\nto breathe in this room, it's too small somehow.",
        0,
        "It seems to be locked from the other side.",
        "It seems to be locked from the other side.",
        "A makeshift altar rests against the back wall. Tiny animal bones and black\nfeathers hang from every corner and crevice.\nA miniature sculpture sits in the middle of the altar.",
        "A makeshift altar rests against the back wall. Tiny animal bones and black\nfeathers hang from every corner and crevice.",
        "The charred remnants of a rocking chair.\nA half-burnt notebook is resting on the melted seat cushion.",
        "The charred remnants of a rocking chair.",
        "This chair is covered in mildew, but otherwise uninteresting.",
        "A vintage dollhouse. Normally you could open it up and take a look inside,\nbut it's been locked with a small silver padlock.",
        "You carefully unlock the padlock and swing the dollhouse open. Eerily, it\nseems to be a miniature version of the house you stand in. Even the\nfurniture is in the same locations.",
        "The open dollhouse watches you impatiently.",
        "The miniature workbench fits perfectly into a space in the garage. The\ndollhouse accepts your gift eagerly.",
        "The miniature sculpture fits perfectly into an alcove in the dining\nroom. You feel your bond with the dollhouse deepen.",
        "A small dresser-drawer is sitting in the corner.\nA small silver key is lying on top, attached to note.",
        "A small dresser-drawer is sitting in the corner.",
        "The wall is strangely spongy here, more like moss than wallpaper.\nThe phrase \"HER CHILDREN\" has been spray-painted across the wall.",
        "An oil painting hangs on the wall, out of place in this shabby room. It\nseems to depict a planet being devoured by... something.\nYou feel that the less you look at it, the better.",
        "A rusty garage shelf.",
        "The shelf is covered with dust, but not much else.",
        "Someone has touched this shelf recently, the dust is noticeably absent.\nA realistic miniature workbench rests on the shelf.",
        "The shelf seems to have been recently used, most of the dust is wiped off.",
        "The shelf is covered with dust, but not much else.",
        "The stairs to the second floor are a wreck - you can't go up this way.",
        "A crude, life-sized sculpture of a pregnant woman. One hand rests on her\nbelly, and the other holds an iron knife.\nThe sculpture's grip looks loose - perhaps you could take the knife.",
        "With a tug, the sculpture releases the knife.\n%y%0 You have obtained iron knife.",
        "A crude, life-sized sculpture of a pregnant woman. One hand rests on her\nbelly.",
        "The dining room table is smashed to splinters. A black, sticky substance\nthat smells like burning hair covers most of the table.",
        "A life-sized sculpture of a woman. She holds in her arms a creature, all\nlegs, heads, and arms, reaching upwards in celebration.\nOne baby fist is clutching something round and shiny.",
        "You reach carefully through the tangled limbs.\n%y%0 You have obtained engraved coin.",
        "A life-sized sculpture of a woman. She holds in her arms a creature, all\nlegs, heads, and arms, reaching upwards in celebration.",
        "A sturdy wood and metal workbench, littered with debris.\nLying amidst the junk and broken tools, you spot a screwdriver.",
        "A sturdy wood and metal workbench, littered with debris.",
        0,
        0,
        0,
        [
            "engraved coin",
            "An ancient coin engraved on both\nsides with a short verse:\n\n\"Yidhra, Dream Witch,\n I am your child.\n Walk with me.\""
        ],
        0,
        0,
        0,
        0,
        [
            "SHRINE",
            "This storage closet has been converted into some kind of shrine. The\nunpainted wooden walls are carved with words, but none of them make\nany sense to you."
        ],
        [
            "DINING ROOM",
            "The dining room is somber and quiet. The walls are covered with\nfaded squares where paintings used to hang."
        ],
        [
            "DRAWING ROOM",
            "You are in a dimly lit drawing room filled with faded furniture.\nThe room smells of musty upholstery."
        ],
        [
            "FOYER",
            "You are in the foyer. The peeling paint and threadbare rugs seem even\nolder than the outside of the house.\nA large dollhouse sits on a pedestal in the far corner of the room."
        ],
        [
            "GARAGE",
            "The garage is empty, save for a few rusty shelves and the usual cobwebs.\nThere must have been other furniture here recently, you can see lines\nin the dust where a workbench used to be."
        ],
        [
            "GARAGE",
            "The garage is empty, save for a few rusty shelves and the usual cobwebs.\nThere is a sturdy workbench near the door."
        ],
        [
            "CHARRED HALLWAY",
            "There must have been a fire at some point. Soot and grime coat the walls,\nand the air stinks of burnt fabric."
        ],
        0,
        0,
        0,
        0,
        0,
        [
            "iron knife",
            "A large iron knife etched with\ntiny symbols. It feels heavy\nin your hand."
        ],
        [
            "small silver key",
            "A small silver key. A note is\nattached with a piece of twine.\n\n\"N is still here, stay on this\n side.\""
        ],
        [
            "your uncle's letter",
            "\"Dearest Emily,\n\n We are all in grave danger and\n I am running out of time. I\n cannot explain here but I need\n your help.\"\n[The rest of the letter has been\ncrossed out and is illegible.]"
        ],
        [
            "half-burnt notebook",
            "Most of the pages are too burnt\nto read, but somehow one page\nis crystal clear:\n\n\"Our Goddess walks the hills\n in the shadow of the keening star\n and we follow in her path\""
        ],
        [
            "miniature workbench",
            "A curiously realistic miniature\nworkbench, made of wood and metal.\nMaybe there's some use for it."
        ],
        [
            "miniature sculpture",
            "A miniature sculpture of a woman,\nvery like the one you saw in\nthe drawing room.\nMaybe there's some use for it."
        ],
        [
            "screwdriver",
            "A rusty, but still functional,\ncrosshead screwdriver."
        ]
    ]
}
/* </generated-data> */
;
