// World
//
// This file is generated by `gulp buildAssets`.

export const World =
/* <generated> */
{ floors:
   [ { name: '1F',
       tiles:
        [ [ 32, 32, 32, 1, 1, 32, 32, 32, 32, 32 ],
          [ 5, 1, 1, 46, 46, 1, 1, 1, 1, 6 ],
          [ 0, 136, 46, 46, 46, 46, 46, 46, 46, 0 ],
          [ 0, 136, 46, 46, 46, 46, 46, 46, 117, 0 ],
          [ 0, 136, 46, 46, 46, 46, 46, 46, 46, 0 ],
          [ 0, 136, 46, 46, 46, 46, 46, 46, 46, 0 ],
          [ 0, 136, 46, 46, 46, 46, 46, 46, 46, 0 ],
          [ 0, 136, 46, 46, 46, 46, 46, 46, 46, 0 ],
          [ 0, 136, 117, 46, 46, 46, 46, 46, 46, 0 ],
          [ 4, 1, 1, 1, 1, 1, 1, 1, 1, 32 ] ],
       rooms:
        [ { id: 1,
            name: 'RSTUDY',
            x: 1,
            y: 0,
            width: 9,
            height: 8,
            objectType: 'object',
            props: {} } ],
       objects: [ { id: 3, name: 'FPLANT', x: 2, y: 1, objectType: 'object', props: {} } ],
       id: 0 } ],
  bounds: [ [ 0, 0 ], [ 10, 10 ] ],
  spawn: [ 7, 7, 0 ],
  strings: { foo: 'bar', RSTUDY: 'A nice old room.\nWhat a nice place it is.\nFuck it.\n' } }
/* </generated> */
;
